name: GameFramework
version: '${version}'
main: org.mmga.gameframework.GameFramework
authors: [ MakeMinecraftGreatAgainTeam ]
description: A Simple Game Framework OpenSource
website: https://github.com/MakeMinecraftGreatAgainTeam/GameFramework
depend:
  - 'Multiverse-Core'
  - 'PlaceholderAPI'
